# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Storage4Grid
email: storage4grid@ismb.it
description: > # this means to ignore newlines until "baseurl:"
   This project receives funding from the European Union’s Horizon 2020 Framework Programme for Research and Innovation under grant agreement no 731155. Copyright © 2016, the Storage4Grid Consortium.
baseurl: "/storage4grid" # the subpath of your site, e.g. /blog
url: "http://storage4grid.eu" # the base hostname & protocol for your site
twitter_username: storage4grid_eu
github_username:  storage4grid
owner: The Storage4Grid Consortium
repository: storage4grid/storage4grid.github.io
# Google services
google_analytics: UA-87628201-1

# Build settings
markdown: kramdown
theme: minima
